apiVersion: v1
kind: Service
metadata:
  name: gelato-api
  namespace: gelato
  labels:
    app.kubernetes.io/name: gelato-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: gelato-recipes-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gelato-api
  ports:
    - name: http
      port: 3001
      targetPort: 3001
