apiVersion: batch/v1
kind: Job
metadata:
  name: gelato-api-migrate
  namespace: gelato
  labels:
    app.kubernetes.io/name: gelato-api-migrate
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: gelato-recipes-platform
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gelato-api-migrate
        app.kubernetes.io/part-of: gelato-recipes-platform
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: migrate
          image: ghcr.io/94manuel/gelato-api:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "npx prisma migrate deploy --schema prisma/schema.prisma"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gelato-postgres-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
