apiVersion: v1
kind: Secret
metadata:
  name: gelato-postgres-secret
  namespace: gelato
type: Opaque
stringData:
  DATABASE_URL: "postgresql://gelato_user:CHANGE_ME@postgres.database.svc.cluster.local:5432/gelato?schema=public"
